import type { DisclosureTarget } from '@/lib/disclosure/types';

/** 15 organizations — 5 per vertical for unified responsible disclosure batch */
export const DISCLOSURE_TARGETS: DisclosureTarget[] = [
  // YC AI SaaS (5)
  {
    id: 'agentgpt',
    slug: 'agentgpt',
    organizationName: 'AgentGPT (Reworkd)',
    vertical: 'yc-ai-saas',
    scanKind: 'github',
    scanSurface: 'https://github.com/reworkd/AgentGPT',
    referenceUrl: 'https://github.com/reworkd/AgentGPT',
    github: 'reworkd/AgentGPT',
  },
  {
    id: 'crewai',
    slug: 'crewai',
    organizationName: 'CrewAI',
    vertical: 'yc-ai-saas',
    scanKind: 'github',
    scanSurface: 'https://github.com/crewAIInc/crewAI',
    referenceUrl: 'https://github.com/crewAIInc/crewAI',
    github: 'crewAIInc/crewAI',
  },
  {
    id: 'dify',
    slug: 'dify-ai',
    organizationName: 'Dify AI',
    vertical: 'yc-ai-saas',
    scanKind: 'github',
    scanSurface: 'https://github.com/langgenius/dify',
    referenceUrl: 'https://github.com/langgenius/dify',
    github: 'langgenius/dify',
  },
  {
    id: 'flowise',
    slug: 'flowise',
    organizationName: 'Flowise AI',
    vertical: 'yc-ai-saas',
    scanKind: 'github',
    scanSurface: 'https://github.com/FlowiseAI/Flowise',
    referenceUrl: 'https://github.com/FlowiseAI/Flowise',
    github: 'FlowiseAI/Flowise',
  },
  {
    id: 'superagent',
    slug: 'superagent',
    organizationName: 'Superagent',
    vertical: 'yc-ai-saas',
    scanKind: 'github',
    scanSurface: 'https://github.com/superagent-ai/superagent',
    referenceUrl: 'https://github.com/superagent-ai/superagent',
    github: 'superagent-ai/superagent',
  },

  // FinTech & Open Banking MCP (5)
  {
    id: 'stripe-mcp',
    slug: 'stripe-mcp',
    organizationName: 'Stripe MCP Server',
    vertical: 'fintech-mcp',
    scanKind: 'github',
    scanSurface: 'https://github.com/modelcontextprotocol/servers/tree/main/src/stripe',
    referenceUrl: 'https://github.com/modelcontextprotocol/servers',
    github: 'modelcontextprotocol/servers',
    contentPath: 'src/stripe',
  },
  {
    id: 'composio-fintech',
    slug: 'composio-fintech',
    organizationName: 'Composio (FinTech Integrations)',
    vertical: 'fintech-mcp',
    scanKind: 'github',
    scanSurface: 'https://github.com/ComposioHQ/composio',
    referenceUrl: 'https://github.com/ComposioHQ/composio',
    github: 'ComposioHQ/composio',
  },
  {
    id: 'n8n-banking',
    slug: 'n8n-open-banking',
    organizationName: 'n8n Open Banking Workflows',
    vertical: 'fintech-mcp',
    scanKind: 'github',
    scanSurface: 'https://github.com/n8n-io/n8n',
    referenceUrl: 'https://github.com/n8n-io/n8n',
    github: 'n8n-io/n8n',
  },
  {
    id: 'activepieces-finance',
    slug: 'activepieces-finance',
    organizationName: 'Activepieces Finance MCP',
    vertical: 'fintech-mcp',
    scanKind: 'github',
    scanSurface: 'https://github.com/activepieces/activepieces',
    referenceUrl: 'https://github.com/activepieces/activepieces',
    github: 'activepieces/activepieces',
  },
  {
    id: 'plaid-mcp-proxy',
    slug: 'plaid-mcp-proxy',
    organizationName: 'Plaid Banking MCP Proxy',
    vertical: 'fintech-mcp',
    scanKind: 'mcp',
    scanSurface: JSON.stringify({
      mcpServers: {
        plaid: {
          command: 'node',
          args: ['plaid-mcp-server.js'],
          tools: ['transfer_funds', 'read_accounts', 'bulk_export_transactions'],
        },
      },
    }),
    referenceUrl: 'https://plaid.com/docs/api/',
  },

  // Enterprise TR Tech (5)
  {
    id: 'logo-yazilim',
    slug: 'logo-yazilim',
    organizationName: 'Logo Yazılım',
    vertical: 'enterprise-tr',
    scanKind: 'github',
    scanSurface: 'https://github.com/logo-yazilim',
    referenceUrl: 'https://www.logo.com.tr',
    github: 'logo-yazilim',
  },
  {
    id: 'kocsistem',
    slug: 'kocsistem',
    organizationName: 'KoçSistem',
    vertical: 'enterprise-tr',
    scanKind: 'endpoint',
    scanSurface: 'https://www.kocsistem.com.tr',
    referenceUrl: 'https://www.kocsistem.com.tr',
  },
  {
    id: 'sabancidx',
    slug: 'sabancidx',
    organizationName: 'SabancıDx',
    vertical: 'enterprise-tr',
    scanKind: 'endpoint',
    scanSurface: 'https://www.sabancidx.com',
    referenceUrl: 'https://www.sabancidx.com',
  },
  {
    id: 'eczacibasi-bilisim',
    slug: 'eczacibasi-bilisim',
    organizationName: 'Eczacıbaşı Bilişim',
    vertical: 'enterprise-tr',
    scanKind: 'endpoint',
    scanSurface: 'https://www.eczacibasi.com.tr',
    referenceUrl: 'https://www.eczacibasi.com.tr',
  },
  {
    id: 'turkcell-digital',
    slug: 'turkcell-digital',
    organizationName: 'Turkcell Dijital Servisler',
    vertical: 'enterprise-tr',
    scanKind: 'github',
    scanSurface: 'https://github.com/Turkcell',
    referenceUrl: 'https://www.turkcell.com.tr',
    github: 'Turkcell',
  },
];
