/**
 * P2 Sprint 15-16 — Continuous Agent Red Teaming types.
 */

export type AttackVector =
  | 'PROMPT_INJECTION'
  | 'JAILBREAK'
  | 'TOOL_ABUSE'
  | 'PRIVILEGE_ESCALATION'
  | 'INDIRECT_INJECTION';

export type SimulationRiskRating = 'EXCELLENT' | 'MODERATE' | 'VULNERABLE' | 'CRITICAL';

export interface RedTeamScenario {
  id: string;
  name: string;
  attackVector: AttackVector;
  userIntent: string;
  toolName: string;
  toolArgs: Record<string, unknown>;
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  autoGenerated?: boolean;
}

export interface VectorSimulationOutcome {
  scenarioId: string;
  attackVector: AttackVector;
  blocked: boolean;
  payload: string;
  response: string;
  riskScore: number;
  vulnerability?: string;
}

export interface SimulationResult {
  simulationId: string;
  agentId: string;
  agentName?: string;
  resilienceScore: number;
  riskRating: SimulationRiskRating;
  outcomes: VectorSimulationOutcome[];
  vulnerabilities: string[];
  blockedCount: number;
  exposedCount: number;
  timestamp: string;
  remediated?: string[];
}

export interface RedTeamSimulationInput {
  agentId: string;
  agentName?: string;
  capabilities: string[];
  scenarios?: RedTeamScenario[];
}

export interface AutoRemediateResult {
  simulationId: string;
  remediated: string[];
  remainingVulnerabilities: string[];
  resilienceScoreAfter: number;
}

export function isBlockedOutcome(outcome: VectorSimulationOutcome): boolean {
  return outcome.blocked;
}

export function isExposedOutcome(outcome: VectorSimulationOutcome): boolean {
  return !outcome.blocked;
}
